apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scwvuecom-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  
  rules:
  - host: sancapweather.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: scwvuecom
            port:
              number: 80
